### ISSUE TITLE
ValueError: The optimizer does not seem to reference any FSDP parameters. HINT: Make sure to create the optimizer after setting up the model.

### ISSUE THREAD

**Issue by lijuan-lll** [rasbt/cvpr2023#10]
fabric = Fabric(accelerator="cuda", precision="16-mixed", strategy="fsdp")
fabric.launch()
torch.set_float32_matmul_precision("medium")

model= fabric.setup_module(model)
optimizer = fabric.setup_optimizers(optimizer)

**Comment by lijuan-lll** [comment]
fabric = Fabric(accelerator="cuda", precision="16-mixed", strategy="fsdp")
fabric.launch()
torch.set_float32_matmul_precision("medium")

model= fabric.setup_module(model)
optimizer = fabric.setup_optimizers(optimizer)

**Comment by rasbt** [comment]
I just ran all the scripts and couldn't reproduce this. Maybe you are using an older version that had these issues. Could you paste the version? (It should print at the top when you are running the scripts.

In newer versions, the calls you had above:

```python
model= fabric.setup_module(model)
optimizer = fabric.setup_optimizers(optimizer)
```

can also combined into a single one:

```python
 model, optimizer = fabric.setup(model, optimizer)
```

Please feel free to reopen if the issue persists. Happy to help further then.
