### ISSUE TITLE
I tried the modification method you mentioned, but the optimizer still reported an error:

### ISSUE THREAD

**Issue by Williamwsk** [rasbt/cvpr2023#4]
> Thanks for the note and sorry about the hassle. I think that's because I had the current dev version installed, which has not been released yet. The new version allows you to combine the two lines
> 
> ```python
>     model = fabric.setup_module(model)
>     optimizer = fabric.setup_optimizers(optimizer)
> ```
> 
> into a single line
> 
> ```python
>     model, optimizer = fabric.setup(model, optimizer)
> ```
> 
> But for the latest stable release, the 2 separate lines are necessary. I updated the code accordingly.

I tried the modification method you mentioned, but the optimizer still reported an error:
```python
File "/project/Code/Skin/aa.py", line 21, in <module>
    main()
  File "/project/Code/Skin/aa.py", line 15, in main
    optimizer = fabric.setup_optimizers(optimizer)
  File "/opt/conda/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 289, in setup_optimizers
    optimizers = [self._strategy.setup_optimizer(optimizer) for optimizer in optimizers]
  File "/opt/conda/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 289, in <listcomp>
    optimizers = [self._strategy.setup_optimizer(optimizer) for optimizer in optimizers]
  File "/opt/conda/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/strategies/fsdp.py", line 213, in setup_optimizer
    raise ValueError(
ValueError: The optimizer does not seem to reference any FSDP parameters. HINT: Make sure to create the optimizer after setting up the model.
```
My environment and related library versions are as follows:
```python
python                   3.10
numpy                    1.26.0
scipy                    1.11.3
pandas                   2.1.1
watermark                2.4.3
lightning                2.0.9.post0
torch                    2.0.1
torchaudio               2.0.2
torchmetrics             1.2.0
torchvision              0.15.2
transformers             4.34.0
deepspeed                0.11.0
``` 

_Originally posted by @Williamwsk in https://github.com/rasbt/cvpr2023/issues/3#issuecomment-1752261562_

**Comment by rasbt** [comment]
Arg, not sure where the problem is coming from. But good news is that `lightning==2.1.0` is now available, which supports the 

 I changed it back to the previous

```python
model, optimizer = fabric.setup(model, optimizer)
```

which should work now and address the issue.
