### ISSUE TITLE
@Williamwsk  I added an example and readme for loading the checkpoints with Fabric here: https://github.com/rasbt/cvpr2023/tree/main/08_saving-and-loading

### ISSUE THREAD

**Issue by Williamwsk** [rasbt/cvpr2023#8]
@Williamwsk  I added an example and readme for loading the checkpoints with Fabric here: https://github.com/rasbt/cvpr2023/tree/main/08_saving-and-loading

I hope this helps!

_Originally posted by @rasbt in https://github.com/rasbt/cvpr2023/issues/5#issuecomment-1777615174_

Thank you very much for your reply。After making changes according to the code you gave me, I found that the code in the training function was executed multiple times (The number of repetitions is consistent with the number of GPUs), such as the model training accuracy output, the number of times the weights were saved, etc. were also executed multiple times. How should I change this situation? It seems that the latest model will not be automatically overwritten when fabric.save().

In addition, I would like to ask you how to transfer the model weight file saved with fabric.save() to the model weight file of pytorch.save()? Because some subsequent operations need to use the .pth weight file to do other work. Looking forward to your reply, thank you very much!

**Comment by rasbt** [comment]
> After making changes according to the code you gave me, I found that the code in the training function was executed multiple times

is this happening with the code in this repo or your code specifically.

> In addition, I would like to ask you how to transfer the model weight file saved with fabric.save() to the model weight file of pytorch.save()?

Oh, good point. I forgot to explain the advantage/difference of `fabric.save`: it lets you save additional information like the optimizer and scheduler state all in one file, which is super useful for checkpointing.

If you just need the model weight file, I would just save it with regular `torch.save(model.state_dict())`.

There's also a 

```python
fabric.load_raw("path/to/model.pt", model)
``` 

function which is equivalent to

```python
model.load_state_dict(torch.load("path/to/model.pt"))
```

**Comment by Williamwsk** [comment]
> > After making changes according to the code you gave me, I found that the code in the training function was executed multiple times
> 
> is this happening with the code in this repo or your code specifically.
> 
> > In addition, I would like to ask you how to transfer the model weight file saved with fabric.save() to the model weight file of pytorch.save()?
> 
> Oh, good point. I forgot to explain the advantage/difference of `fabric.save`: it lets you save additional information like the optimizer and scheduler state all in one file, which is super useful for checkpointing.
> 
> If you just need the model weight file, I would just save it with regular `torch.save(model.state_dict())`.
> 
> There's also a
> 
> ```python
> fabric.load_raw("path/to/model.pt", model)
> ```
> 
> function which is equivalent to
> 
> ```python
> model.load_state_dict(torch.load("path/to/model.pt"))
> ```


I still have a problem with debugging here, and I would like to ask you for advice again. First, my training code is as follows:
```python
fabric = L.Fabric(accelerator='cuda', precision='bf16-mixed', devices=torch.cuda.device_count(), strategy='FSDP')
...
state = {"epoch": epoch, "model": model_restoration, "optimizer": optimizer}
fabric.save(os.path.join(model_dir, "model_iter_best.ckpt"), state)
``` 

Four 3090 GPUs were used during training, and then an error was reported three times when saving. The error results each time are as follows::
```python
File "/project/Code/Skin/train_distill_accelerate.py", line 424, in <module>
    main()
  File "/project/Code/Skin/train_distill_accelerate.py", line 343, in main
    fabric.save(os.path.join(model_dir, "model_iter_best.ckpt"), state)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 738, in save
    self._strategy.save_checkpoint(path=path, state=_unwrap_objects(state), filter=filter)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/strategies/fsdp.py", line 435, in save_checkpoint
    raise FileExistsError(f"The checkpoint directory already exists and is not empty: {path}")
FileExistsError: The checkpoint directory already exists and is not empty: /project/Code/Skin/work_dirs/1020/skin_1020_teacher_accelerate/models/model_iter_best.ckpt
``` 

Secondly, when reading the weight of the sharding model saved above, the error code and error result when reading are as follows:
```python
...
weight_file = './work_dirs/1020/skin_1020_teacher_accelerate/models/model_iter_best.ckpt'
state = {"model": model_restoration, "optimizer": optimizer}
fabric.load(weight_file, state)
print('fabric_loading_pretrained_model!!!!!!')
...
``` 
```python
Traceback (most recent call last):
  File "/project/Code/Skin/train_distill_accelerate_load.py", line 427, in <module>
    main()
  File "/project/Code/Skin/train_distill_accelerate_load.py", line 248, in main
    fabric.load(weight_file, state)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 764, in load
    remainder = self._strategy.load_checkpoint(path=path, state=unwrapped_state, strict=strict)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/lightning/fabric/strategies/fsdp.py", line 569, in load_checkpoint
    optim_state = load_sharded_optimizer_state_dict(
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/distributed/checkpoint/optimizer.py", line 294, in load_sharded_optimizer_state_dict
    state_dict[key] = _shard_tensor(
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/distributed/_shard/api.py", line 68, in _shard_tensor
    st = sharding_spec.shard(tensor, src_rank=src_rank, process_group=process_group)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py", line 181, in shard
    dist.scatter(
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3139, in scatter
    _check_tensor_list(scatter_list, "scatter_list")
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 807, in _check_tensor_list
    raise RuntimeError(
RuntimeError: Invalid function argument. Expected parameter `scatter_list` to be of type List[torch.Tensor].
``` 
If I use 4 GPUs for training and 1 GPU for reading, I find that the training acceleration slows down and the training gets stuck. I hope you can give me a complete example of saving and reading model weights using multi-card training and multi-card breakpoint resume (i.e. resume) training to solve my case. 

Finally, as you replied last night, the code that only saves the model after using Lightning.Fabric(), the model size saved by torch.save(model.state_dict()) is different from the model size saved by the pure pytorch code, and the same error is reported.

Secondly, I understand that the meaning of Lightning.Fabric model acceleration is to speed up training, but it does not affect the normal saving and reading of pytorch models. Otherwise, there are various restrictions on saving and reading, and if it cannot be interoperated with pytorch, it may cause problems. It affects the promotion and use of the Lightning.Fabric library. After all, the ecology of pytorch is relatively complete and can be converted to multiple training or inference frameworks.(this statement does not question the contribution of you and your team, but only discusses personal opinions. I hope You can understand). Looking forward to your reply, thank you very much!

**Comment by rasbt** [comment]
> FileExistsError: The checkpoint directory already exists and is not empty: /project/Code/Skin/work_dirs/1020/skin_1020_teacher_accelerate/models/model_iter_best.ckpt

In that case it would not override an existing checkpoint file. You'd have to manually delete it  before the next run. 

you can add 

```python
if os.path.exists("model_iter_best.ckpt"):
    os.remove("model_iter_best.ckpt")
```

Perhaps there should be a `override=True` feature in the future to automatically enable that.

> RuntimeError: Invalid function argument. Expected parameter `scatter_list` to be of type List[torch.Tensor].

I am having the same issues. I pinged the developer.

**Comment by Williamwsk** [comment]
> > FileExistsError：检查点目录已存在且不为空：/project/Code/Skin/work_dirs/1020/skin_1020_teacher_accelerate/models/model_iter_best.ckpt
> 
> 在这种情况下，它不会覆盖现有的检查点文件。您必须在下次运行之前手动删除它。
> 
> 你可以加
> 
> ```python
> if os.path.exists("model_iter_best.ckpt"):
>     os.remove("model_iter_best.ckpt")
> ```
> 
> `override=True`也许将来应该有一个功能可以自动启用它。
> 
> > 运行时错误：函数参数无效。预期参数的`scatter_list`类型为 List[torch.Tensor]。
> 
> 我也有同样的问题。我联系了开发商。


I have used this line of code 
```python
if os.path.exists("model_iter_best.ckpt"):
    os.remove("model_iter_best.ckpt")
``` 

At present, my problem is the problem of saving and reading the model, which prevents me from getting through the entire process. The second problem is the mutual conversion problem between Fabric saving model and pytorch model. This is related to the promotion and use of Fabric, otherwise it is just a tentative experiment. That’s it, it cannot be applied on a large scale.

**Comment by rasbt** [comment]
> conversion problem between Fabric saving model and pytorch model

I am wondering which issue you are bumping into with `fabric.save` when deleting the checkpoint files? The saved checkpoint file contains the PyTorch model. If you just want to save the pure pytorch model from there, you could use `torch.save(model.state_dict()`, and in distributed contexts the regular

```python
with model.summon_full_params():
    torch.save(model.state_dict(), 'model_path.pt')
```

As far as I know, Fabric should not prevent you from using that.
